In [25]:
import numpy as np
import pandas as pd

# 1. How likely is it that you roll doubles when rolling two dice?

In [26]:
rolls = pd.DataFrame()
rolls['die1']= np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
rolls['die2'] = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
rolls.head()

die1  die2
0     2     4
1     4     1
2     1     4
3     5     2
4     2     3

In [27]:
rolls['is_pair'] = rolls.die1 == rolls.die2
rolls.is_pair.mean()

0.16693

In [28]:
#doubles_list=[[1, 1],[2, 2],[3, 3],[4, 4], [5, 5], [6,6]]

#n_trials = nrows = 10_000
#n_dice = ncols = 2

#rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
#rolls

#doubles_by_trial
    
#    for n in rolls:
#doubles_by_trial = doubles_by_trial.append(n)
#doubles_by_trial

# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [31]:
n_trials = nrows = 10_000
n_coins = ncols = 8

flips = np.random.choice([1, 0], n_trials * n_coins).reshape(nrows, ncols)
flips

array([[0, 1, 0, ..., 1, 1, 1],
       [0, 1, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 1, ..., 1, 0, 1]])

In [32]:
number_of_heads = flips.sum(axis=1)

In [33]:
flips[0]

array([0, 1, 0, 1, 0, 1, 1, 1])

In [34]:
number_of_heads[0]

5

In [35]:
number_of_heads

array([5, 3, 5, ..., 2, 2, 4])

# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [38]:
df = pd.DataFrame(outcomes)
df.columnns = ['first_billboard', 'second_billboard']
df.head()

NameError: name 'outcomes' is not defined

In [ ]:
df['both_ds'] = (df.first_billboard == "Data Science") & (df.second+billboard == "Data Science")
df['both_ds'].mean()

In [ ]:
# Therorictal possiblity
.25 * .25

# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

# 5. Compare Heights
* Men have an average height of 178 cm and standard deviation of 8cm.
* Women have a mean of 170, sd = 6cm.
* If a man and woman are chosen at random, P(woman taller than man)?

# 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 

* What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

* What is the probability that we observe an installation issue within the first 150 students that download anaconda?

* How likely is it that 450 students all download anaconda without an issue?

# 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days.
* How unlikely is this?
* How likely is it that a food truck will show up sometime this week?

# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?