In [2]:
import numpy as np
import pandas as pd

# 1. How likely is it that you roll doubles when rolling two dice?

In [3]:
rolls = pd.DataFrame()
rolls['die1']= np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
rolls['die2'] = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
rolls.head()

die1  die2
0     2     2
1     1     5
2     4     4
3     5     4
4     1     4

In [4]:
rolls['is_pair'] = rolls.die1 == rolls.die2
rolls.is_pair.mean()
# Probability of rolling doubles

0.16399

In [5]:
#first try on problem

#doubles_list=[[1, 1],[2, 2],[3, 3],[4, 4], [5, 5], [6,6]]

#n_trials = nrows = 10_000
#n_dice = ncols = 2

#rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
#rolls

#doubles_by_trial
    
#    for n in rolls:
#doubles_by_trial = doubles_by_trial.append(n)
#doubles_by_trial

# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [6]:
n_trials = nrows = 10_000
n_coins = ncols = 8

flips = np.random.choice([1, 0], n_trials * n_coins).reshape(nrows, ncols)
flips

array([[1, 0, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [7]:
number_of_heads = flips.sum(axis=1)

In [8]:
flips[0]

array([1, 0, 0, 0, 0, 1, 1, 0])

In [9]:
number_of_heads[0]

3

In [10]:
number_of_heads

array([3, 4, 4, ..., 4, 4, 3])

In [11]:
# Probability of getting exactly 3 heads per 8 coin flips
(number_of_heads == 3).mean()

0.2204

In [12]:
# Probability of getting more than 3 heads per 8 coin flips
(number_of_heads > 3).mean()

0.6311

# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [14]:
outcomes = np.random.choice(["Web Dev","Data Science"], size=(100_000,2),p=[.75,.25])
outcomes

array([['Data Science', 'Web Dev'],
       ['Web Dev', 'Data Science'],
       ['Data Science', 'Data Science'],
       ...,
       ['Web Dev', 'Data Science'],
       ['Web Dev', 'Data Science'],
       ['Web Dev', 'Web Dev']], dtype='<U12')

In [19]:
outcomes_df = pd.DataFrame(outcomes)
outcomes_df.columns = ['first_billboard', 'second_billboard']
outcomes_df.head()

first_billboard second_billboard
0    Data Science          Web Dev
1         Web Dev     Data Science
2    Data Science     Data Science
3    Data Science          Web Dev
4         Web Dev          Web Dev

In [21]:
# Probability of driving past billboards that both feature Data Science students
outcomes_df['both_ds'] = (outcomes_df.first_billboard == "Data Science") & (outcomes_df.second_billboard == "Data Science")
outcomes_df['both_ds'].mean()

0.06296

In [ ]:
# Therorictal possiblity
.25 * .25

# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [23]:
num_of_days = 5
poptart_consumption = np.round(np.random.normal(loc=3,scale=.5,size=(100_000, num_of_days)))
poptart_consumption

array([[2., 3., 3., 3., 3.],
       [3., 3., 2., 3., 3.],
       [3., 3., 3., 2., 4.],
       ...,
       [4., 3., 4., 3., 3.],
       [4., 3., 2., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [24]:
weekly_demand = poptart_consumption.sum(axis=1)

In [25]:
# Probability of being able to buy poptarts on Friday afternoon
(weekly_demand < 17).mean()

0.88669

# 5. Compare Heights
* Men have an average height of 178 cm and standard deviation of 8cm.
* Women have a mean of 170, sd = 6cm.
* If a man and woman are chosen at random, P(woman taller than man)?

In [28]:
men = np.random.normal(178, 8, size=100_000)
women = np.random.normal(170, 6, size=100_000)

In [29]:
# Probability of a woman being taller than a man
(men < women).mean()

0.21147

# 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 

* What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

* What is the probability that we observe an installation issue within the first 150 students that download anaconda?

* How likely is it that 450 students all download anaconda without an issue?

In [30]:
trials = 100_000

In [33]:
students_per_trial = 50
# 0 is fail, 1 is success

installs = np.random.choice([0,1], size=(trials, students_per_trial), p=[1/250, 249/250])
installs

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [34]:
installs_df = pd.DataFrame(installs)
installs_df.head()

0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
1   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
2   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
3   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   
4   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   

   47  48  49  
0   1   1   1  
1   1   1   1  
2   1   1   1  
3   1   1   1  
4   1   1   1  

[5 rows x 50 columns]

# 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days.
* How unlikely is this?
* How likely is it that a food truck will show up sometime this week?

# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?